### ISSUE TITLE
Not working on 1.38

### ISSUE THREAD

**Issue by aexvir** [lehni/vscode-titlebar-less-macos#38]
It seems that the last update broke some of the patches that this extension applies. I've checked the console output and it seems because some files don't exist anymore, in this case they seem to have been renamed

```javascript
[Extension Host] Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js'    at Object.openSync (fs.js:436:3)    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)    at Object.readFileSync (fs.js:341:35)    at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:580:40)    at applyPatches (/Users/alex/.vscode/extensions/lehni.vscode-titlebar-less-macos-1.9.1/extension.js:164:26)
```

```javascript
[Extension Host] Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'    at Object.openSync (fs.js:436:3)    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)    at Object.readFileSync (fs.js:341:35)    at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:580:40)    at applyPatches (/Users/alex/.vscode/extensions/lehni.vscode-titlebar-less-macos-1.9.1/extension.js:164:26)
```

It seems that the new files are called `workbench.desktop.main.js` and `workbench.desktop.main.css` respectively

**Comment by lehni** [comment]
Yes, I'm aware. Sadly I'm fully absorbed by work currently, and can't fix this right now. it'll be another 3 weeks or so until I can make some time for this.
